channels:
  - main
  - conda-forge
  - anaconda
dependencies:
  - python=3.12
#  - appmode
#  - beautifulsoup4
  - bokeh
#  - boto
#  - ipydatawidgets
  - ipympl
#  - ipython
#  - ipywidgets
  - jedi-language-server
#  - jupyter_contrib_nbextensions
#  - jupyter_nbextensions_configurator
  - jupyter-book
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-language-pack-de-DE
  - jupyterlab-lsp
  - jupyterlab_rise
#  - jupyterlab-mathjax3
  - jupytext
  - keras
  - keyboard
  - mariadb
  - matplotlib
  - metakernel
  - nbgitpuller
  - numpy
  - ollama
  - ollama-python
  - openpyxl            
  - pandas
#  - pgzero
  - pillow
  - pip
  - plotly
  - prettytable
  - pycryptodome
  - pydot
  - pylint
  - pytorch
  - requests
  - rise
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - tabulate
  - tensorflow
  - tikzmagic
  - wheel
#  - widgetsnbextension
#  - yapf
  - pip:
#    - bokeh-sampledata
#    - jupyterlab_latex
#    - ipyturtle
    - jturtle
#    - jupyterlab-widgets
#    - mobilechelonian
#    - mysql-connector
    - pedal
#    - pygame-ce
#    - tkinter