channels:
  - jetbrains
dependencies:
  - r-base=3.6
  - r-irkernel=1.1
  - python=3.7
  - nbgitpuller
  - jupyterlab-git
  - rise
  - xeus-cling
  - xeus-sqlite
  - sqlite
  - soci-mysql
  - soci-postgresql
  - soci-sqlite
  - metakernel
  - octave
  - texinfo
  - octave_kernel
  - openjdk
  - kotlin-jupyter-kernel
  - bash_kernel
  - setuptools
  - ipywidgets
  - ipyvolume
  - appmode
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - tensorflow
  - scipy
  - keras
  - scikit-learn
  - scrapy
  - beautifulsoup4
  - plotly
  - pydot
  - bokeh
  - pytorch
  - boto
  - requests
  - pillow
  - elm
  - r-devtools
  - r-tidyverse
  - r-rmarkdown
  - r-httr
  - r-shinydashboard
  - r-leaflet
  - r-caret
  - r-dplyr
  - r-scales
  - r-units
  - r-formatR
  - coq-jupyter
  - pip
  - pip:
    - emu86
    - jupyter-c-kernel
    - elm_kernel
    - jupyterlab_latex
    - gnuplot_kernel
