channels:
  - main
  - conda-forge
  - anaconda
dependencies:
  -	python
  -	appmode
  -	beautifulsoup4
  -	bokeh
  -	bokeh-sampledata
  -	boto
  -	distutils
  -	ipydatawidgets
  -	ipympl
  -	ipython
  -	ipywidgets
  -	jedi-language-server
  -	jturtle
  -	jupyter_contrib_nbextensions
  -	jupyter_nbextensions_configurator
  -	jupyter-book
  -	jupyterlab
  -	jupyterlab-git
  -	jupyterlab-language-pack-de-DE
  -	jupyterlab-lsp
  -	jupyterlab-widgets
  -	jupytext
  -	keras
  -	keyboard
  -	mariadb
  -	matplotlib
  -	metakernel
  -	mysql-connector
  -	nbgitpuller
  -	numpy
  -	pandas
  -	pedal
  -	pgzero
  -	pillow
  -	pip
  -	plotly
  -	prettytable
  -	pycryptodome
  -	pydot
  -	pygame-ce
  -	pylint
  -	pytorch
  -	requests
  -	rise
  -	scikit-learn
  -	scipy
  -	scrapy
  -	seaborn
  -	tabulate
  -	tensorflow
  -	tikzmagic
  -	tkinter
  -	wheel
  -	widgetsnbextension
  -	yapf
  - pip:
    - jupyterlab_latex
    - ipyturtle
    - mobilechelonian
