channels:
  - main
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - nbgitpuller
  - jupyterlab-git
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - tikzmagic
  - rise
  - yapf
  - ipywidgets
  - widgetsnbextension
  - metakernel
  - appmode
  - numpy
  - pycryptodome
  - matplotlib
  - pandas
  - seaborn
  - tensorflow
  - scipy
  - keras
  - scikit-learn
  - scrapy
  - beautifulsoup4
  - plotly
  - pydot
  - bokeh
  - pytorch
  - boto
  - requests
  - pillow
  - pip
  - Pillow
  - pip:
    - jupyterlab_latex
    - ipyturtle
    - mobilechelonian
