#!/bin/bash
chmod +x postBuild.d/*.sh

for file in postBuild.d/*.sh; do
    [ -f "$file" ] || continue
    $file
done

echo 'exec "$@"' >> ~/start

jupyter kernelspec list > ~/kernel.list

rm -rf postBuild.*
rm -rf .git
rm -rf ressources
rm -rf .cache
rm -rf .yarn
rm -rf .cpan
rm -rf .cpanm
rm -rf .empty
rm .gitignore
rm *.toml
rm *.R
rm *.txt
rm *.yml
rm *.md
rm LICENSE
rm -- "$0"
